library(dplyr)
library(stringr)
library(here)
library(binance)

COINS_SCRIPT <- here("R", "coins.R")

symbols <- market_exchange_info()$symbols

coins <- c(symbols$base, symbols$quote) %>%
  unique() %>%
  sort()

cat("# Generated by get-coins.R. Do not edit!\n#\n", file = COINS_SCRIPT)

paste(deparse(coins), collapse = "") %>%
  str_replace_all("\"", "'") %>%
  str_replace_all("',", "',\n ") %>%
  str_replace_all("'\\)", "'\n)") %>%
  str_replace_all("\\('", "(\n  '") %>%
  cat("COINS <-", ., file = COINS_SCRIPT, append = TRUE)
